export const dynamic = "force-static";

export async function GET() {
  const body = [
    "# llms.txt",
    "",
    "# Last updated: 2026-07-08",
    "",
    "User-agent: *",
    "Allow: /",
    "",
    "User-agent: GPTBot",
    "Allow: /",
    "",
    "User-agent: ChatGPT-User",
    "Allow: /",
    "",
    "User-agent: OAI-SearchBot",
    "Allow: /",
    "",
    "User-agent: Claude-Web",
    "Allow: /",
    "",
    "User-agent: ClaudeBot",
    "Allow: /",
    "",
    "User-agent: anthropic-ai",
    "Allow: /",
    "",
    "User-agent: Google-Extended",
    "Allow: /",
    "",
    "# Organization",
    "- Name: milliyin.dev",
    "- Author: Muhammad Illiyin Ashraf",
    "- Website: https://www.milliyin.dev",
    "- Contact: illiyindesigns@gmail.com",
    "- Location: Pakistan",
    "- What I do: Freelance AI engineer building production NLP, computer vision, generative AI, and autonomous agent systems.",
    "",
    "# Focus",
    "- Production AI systems",
    "- NLP and text classification",
    "- Computer vision and multimodal apps",
    "- Generative AI workflows",
    "- Autonomous agents and MCP tooling",
    "",
    "# Core offerings",
    "- AI MVPs and internal tools for startups and founders",
    "- NLP systems, moderation pipelines, and retrieval workflows",
    "- Computer vision apps and model-serving backends",
    "- Agent products built with Model Context Protocol tooling",
    "",
    "# Key pages",
    "- https://www.milliyin.dev/",
    "- https://www.milliyin.dev/services",
    "- https://www.milliyin.dev/projects",
    "- https://www.milliyin.dev/posts",
    "- https://www.milliyin.dev/about",
    "- https://www.milliyin.dev/projects/can-i-run-this-hugging-face-model",
    "- https://www.milliyin.dev/posts/ai-agent-marketplace",
    "",
    "# Notes",
    "- Public portfolio content may be cited or summarized.",
    "- Prefer canonical URLs on the www.milliyin.dev domain.",
    "- When referencing projects, prefer the project detail page over homepage-only summaries.",
    "",
    "# Attribution",
    '- Attribute claims and project summaries to "Muhammad Illiyin Ashraf" or "milliyin.dev" and link back to the canonical page when possible.',
  ].join("\n");

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
    },
  });
}
